Discord:
  BotToken: YOUR_BOT_TOKEN
GitHub:
  ClientId: GITHUB_APP_CLIENT_ID
  InstallationId: GITHUB_APP_INSTALLATION_ID
  PemFile: PATH_TO_YOUR_PRIVATE_KEY_PEM_FILE
  Webhook:
    Secret: WEBHOOK_SECRET
