name: build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "renovate.json"
      - ".editorconfig"
      - ".gitattributes"
      - ".gitignore"
      - ".github/**"
      - "LICENSE"
      - "**.md"
      - "docker-compose.yaml"
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ghcr.io/maaassistantarknights/pallas-bot-discord:test
          platforms: linux/amd64
