name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  docker:
    if: ${{
      !(github.event_name == 'push' && contains(github.event.head_commit.message, 'Merge pull request #'))
    }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ghcr.io/maaassistantarknights/pallas-bot-discord:test
          platforms: linux/amd64
